### ISSUE TITLE
QuickDNS 似乎写得有问题

### ISSUE THREAD

**Issue by metahys** [FradSer/Alfred-Workflows-by-FradSer#1]
```
networksetup -setdnsservers networkservice dns1 [dns2] [...]
```

这里应该用networkservice

```
networksetup -setdnsservers ${DEVICE%,*} 114.114.114.114 114.114.115.115
```

但是这里用的却是DEVICE
这导致我用USB Ethernet这个服务的时候无法切换DNS，因为此时USB Ethernet服务的Device是DAD...

我不太熟悉Bash script...没法自己改，不过看到一个思路是用

```
networksetup getinfo "WI-FI"|grep -c "IP address:\W[1-9]"
```

检查networkservice是否有IP address来判断是否处于活跃状态.(http://segmentfault.com/q/1010000000664358)

**Comment by FradSer** [comment]
因为自己一直用的 Wi-Fi 所以没有注意到 USB Ethernet 的问题，我等下该好了之后通知你。

**Comment by FradSer** [comment]
@metahys 按照你思路已经修改完成了。
先打印所有的设备，然后按照链接里面的方便遍历查询是否有 IP，如果有的话输出给修改 DNS 的语句。
我测试了一下，感觉没有问题的。希望你测试完成之后告诉我结果，谢谢！

``` shell
saveIFS="$IFS"
IFS='
'
services=( $(networksetup -listallnetworkservices | sed '/An asterisk ([*]) denotes that a network service is disabled./d; s/^[*]//') )
IFS="$saveIFS"
for i in "${services[@]}"; do
    if [ $(networksetup -getinfo $i | grep -c "IP address:\W[1-9]") -eq 1 ]; then
        echo $i
    fi
done
```

**Comment by enerai** [comment]
请问在输入关键字"dns"之后能不能出来一个列表让用户选择？从而代替手动输入相关字符串？

**Comment by FradSer** [comment]
@enerai 考虑最近优化一下，可以做到。
